# Generated by Django 4.1.7 on 2023-03-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_postitem_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
